
name: solo_fit_leveling_app
description: A Solo Leveling inspired fitness tracker app.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^15.1.0+1
  shared_preferences: ^2.0.15
  audioplayers: ^5.2.0
  timezone: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/tap.mp3
